#!/bin/bash

set -e

service="$1"
requests="$2"
hostname=$(hostname)

if test "x$service" = "x" -o "x$requests" = "x"
then
    echo "usage: provision-soa-service SERVICE SECTOR" >&2
    exit 1
fi

if grep -q "^$service.soa_key =" /etc/SCAMP/soa.conf
then
    echo "changed=no comment='already provisioned'"
    exit 0
fi

mkdir -p /etc/SCAMP/services
openssl req -new -nodes -subj "/CN=$hostname $service/O=SCAMP Inc/C=US/ST=California/L=San Diego" -x509 -days 3650 -newkey rsa:4096 -out /etc/SCAMP/services/$service.crt -keyout /etc/SCAMP/services/$service.key

fingerprint=$( openssl x509 -fingerprint -noout -in /etc/SCAMP/services/$service.crt | sed 's/.*=//' )

echo "$fingerprint    $requests:ALL" >> /etc/SCAMP/authorized_services
echo "$service.soa_key = /etc/SCAMP/services/$service.key" >> /etc/SCAMP/soa.conf
echo "$service.soa_cert = /etc/SCAMP/services/$service.crt" >> /etc/SCAMP/soa.conf

echo "changed=yes comment=provisioned"
