#!/bin/bash

set -e

service="$1"
requests="$2"
hostname=$(hostname)

if [ ! -f /etc/SCAMP/soa.conf ]; then
    echo "'/etc/SCAMP/soa.conf' not present. Run 'scripts/init-system-config'."
    exit 1
fi

if test "x$service" = "x" -o "x$requests" = "x"
then
    echo "usage: provision-soa-service SERVICE SECTOR" >&2
    exit 1
fi

if grep -q "^$service.soa_key =" /etc/SCAMP/soa.conf
then
    echo "changed=no comment='already provisioned'"
    exit 0
fi

mkdir -p /etc/SCAMP/services
export servkey=/etc/SCAMP/services/$service.key
export servcert=/etc/SCAMP/services/$service.crt

openssl genrsa -out $servkey 4096
openssl req -new -nodes -subj "/CN=$hostname $service/O=SCAMP Inc/C=US/ST=California/L=San Diego" -x509 -days 3650 -key $servkey -out $servcert

fingerprint=$( openssl x509 -fingerprint -noout -in $servcert | sed 's/.*=//' )

echo "$fingerprint    $requests:ALL" >> /etc/SCAMP/authorized_services
echo "$service.soa_key = $servkey" >> /etc/SCAMP/soa.conf
echo "$service.soa_cert = $servcert" >> /etc/SCAMP/soa.conf

echo "changed=yes comment=provisioned"
